"""
Auto-generated version information.
DO NOT EDIT THIS FILE MANUALLY!

Generated: 2025-12-25T16:46:21.642422
"""

# Version components
VERSION_MAJOR = 1
VERSION_MINOR = 0
VERSION_PATCH = 5
VERSION_BUILD = 927

# Version strings
VERSION = "1.0.5"
FULL_VERSION = "1.0.5+build.927.902af15.dirty"

# Git information
GIT_COMMIT = "902af15"
GIT_BRANCH = "main"
GIT_TAG = "v1.0.4"
GIT_DIRTY = True

# Build information
BUILD_NUMBER = 927
BUILD_DATE = "2025-12-25T16:46:21.642422"
BUILD_TIMESTAMP = 1766657781

# Human-readable version
def get_version_string():
    """Get human-readable version string."""
    return VERSION

def get_full_version_string():
    """Get full version string with build info."""
    return FULL_VERSION

def get_version_info():
    """Get complete version information as dictionary."""
    return {
        'version': VERSION,
        'full_version': FULL_VERSION,
        'major': VERSION_MAJOR,
        'minor': VERSION_MINOR,
        'patch': VERSION_PATCH,
        'build': VERSION_BUILD,
        'git_commit': GIT_COMMIT,
        'git_branch': GIT_BRANCH,
        'git_tag': GIT_TAG,
        'git_dirty': GIT_DIRTY,
        'build_date': BUILD_DATE,
        'build_timestamp': BUILD_TIMESTAMP,
    }
