"""
Auto-generated version information.
DO NOT EDIT THIS FILE MANUALLY!

Generated: 2025-12-19T07:43:03.236176
"""

# Version components
VERSION_MAJOR = 1
VERSION_MINOR = 0
VERSION_PATCH = 3
VERSION_BUILD = 483

# Version strings
VERSION = "1.0.3"
FULL_VERSION = "1.0.3+build.483.unknown"

# Git information
GIT_COMMIT = "unknown"
GIT_BRANCH = "unknown"
GIT_TAG = "v1.0.3"
GIT_DIRTY = False

# Build information
BUILD_NUMBER = 483
BUILD_DATE = "2025-12-19T07:43:03.236176"
BUILD_TIMESTAMP = 1766106783

# Human-readable version
def get_version_string():
    """Get human-readable version string."""
    return VERSION

def get_full_version_string():
    """Get full version string with build info."""
    return FULL_VERSION

def get_version_info():
    """Get complete version information as dictionary."""
    return {
        'version': VERSION,
        'full_version': FULL_VERSION,
        'major': VERSION_MAJOR,
        'minor': VERSION_MINOR,
        'patch': VERSION_PATCH,
        'build': VERSION_BUILD,
        'git_commit': GIT_COMMIT,
        'git_branch': GIT_BRANCH,
        'git_tag': GIT_TAG,
        'git_dirty': GIT_DIRTY,
        'build_date': BUILD_DATE,
        'build_timestamp': BUILD_TIMESTAMP,
    }
